# Generated by Django 4.2.9 on 2024-02-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='student_images')),
                ('hobby', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
