# Generated by Django 4.2.10 on 2024-02-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='category_image'),
        ),
    ]
