# Generated by Django 4.0 on 2024-03-02 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0008_relatedimage'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0.0)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('purchased', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=30, null=True)),
                ('order_id', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_method', models.CharField(choices=[('Cash_On_Delivery', 'Cash On Delivery'), ('SSLCommerz', 'SSLCommerz')], default='Cash_On_Delivery', max_length=30)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_product', models.ManyToManyField(to='cart.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='auth.user')),
            ],
        ),
    ]
